### ISSUE TITLE
[Bug] KeyError: 'tasks'

### ISSUE THREAD

**Issue by feliperafaelbarbosa** [wfcommons/wfcommons#43]
**WfCommons Information**
- WfCommons version: 1.0
- Python Version: 3.11.2

**Describe the bug**
Hello guys, I'm trying to execute this documentation code but I am have the following problem.
Does this error occur because I'm not using real workflow?

**To Reproduce**
``` python
import pathlib
from wfcommons import Instance
input_instance = pathlib.Path('blast-chameleon-large-001.json')
instance = Instance(input_instance=input_instance)
```

**Expected behavior**
```
Traceback (most recent call last):
  File "/home/felipe/Desktop/meus_testes/wfcommons_instance/main.py", line 5, in <module>
    instance = Instance(input_instance=input_instance)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/felipe/.local/lib/python3.11/site-packages/wfcommons/wfinstances/instance.py", line 68, in __init__
    schema_validator.validate_instance(self.instance)
  File "/home/felipe/.local/lib/python3.11/site-packages/wfcommons/wfinstances/schema.py", line 48, in validate_instance
    self._semantic_validation(data)
  File "/home/felipe/.local/lib/python3.11/site-packages/wfcommons/wfinstances/schema.py", line 116, in _semantic_validation
    for j in data["workflow"]["tasks"]:
             ~~~~~~~~~~~~~~~~^^^^^^^^^
KeyError: 'tasks'
```

**Desktop (please complete the following information):**
 - OS:  Debian
 - Version Bookworm

**Comment by rafaelfsilva** [comment]
@felipetibarbosa, there was a bug for support [WfFormat](https://github.com/wfcommons/WfFormat) v1.5. All should be fixed in the main repository, but we will continue doing some more tests before releasing WfCommons v1.1. Thank you!
